version: '3.8'

services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped
    command: >
      sh -c "ollama serve & sleep 5 && ollama pull llama2 && ollama pull nomic-embed-text && wait"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped

  rag_api:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - ollama
      - redis

volumes:
  ollama-data: